name: .NET 6 - Phase 3 - Step 1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore "./Phase 3/src/02. Step1/Pezza.sln"
    - name: Build
      run: dotnet build "./Phase 3/src/02. Step1/Pezza.sln" --configuration Release --no-restore
