name: .NET 7 - Phase 7 - API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Install dependencies
      run: dotnet restore "./Phase 7/API Solution/Pezza.sln"
    - name: Build
      run: dotnet build "./Phase 7/API Solution/Pezza.sln" --configuration Release --no-restore
